#!/usr/bin/env bash
# PreToolUse hook for Edit|Write. Blocks writes to files this repo does not
# author. gateway/console is build output vendored from fold-run/fold-console;
# gateway/console_source.go is generated and records the commit it came from.
# CI's `console` job re-vendors from the pin and fails on any difference, so an
# edit here cannot merge — blocking it now costs a sentence, and learning it
# from a red PR costs a round trip.
#
# Exit 2 -> block the tool call; stderr is fed back to Claude.
set -uo pipefail

file=$(jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
[[ -z "$file" ]] && exit 0

case "$file" in
  */gateway/console/*)
    echo "Blocked: gateway/console/ is vendored build output from fold-run/fold-console, not source. CI's 'console' job re-vendors from the pin and fails the build on any difference, so this edit cannot merge (CONTRIBUTING.md, 'The console is not maintained here'). Send UI changes to the fold-console repo; bring them here by moving CONSOLE_COMMIT in scripts/sync-console.sh and running 'make sync-console'. See /console-sync." >&2
    exit 2
    ;;
  */gateway/console_source.go)
    echo "Blocked: gateway/console_source.go is generated by scripts/sync-console.sh and records which fold-console commit the vendored bytes came from. Hand-editing it makes the pin describe bytes it did not produce, and 'make console-check' will fail. Move CONSOLE_COMMIT in scripts/sync-console.sh and run 'make sync-console' instead. See /console-sync." >&2
    exit 2
    ;;
esac

exit 0
