package gateway

// consoleSource is the fold-run/fold-console commit that gateway/console was
// vendored from. Generated by scripts/sync-console.sh — do not edit by hand.
//
// It lives here rather than in gateway/console/ because `//go:embed console`
// would sweep up a file in that directory and serve it at GET /console/SOURCE.
// As a Go file it is also covered by `make fmt-check`, and it reaches
// /api/federation so a version-skew question has an answer without unpacking
// the binary.
const consoleSource = "cdd97bafb725fc0d9ba19ef98df46f8f991ff386"
